#!/bin/sh

# check for internet connection
ip route ls | grep -v '' && exit 1

# check if the gpg-agent is running
pgrep gpg-agent >/dev/null || exit 2

while notmuch --config="$HOME/.notmuch-config" new --quiet 2>&1 | grep -v "Ignoring" | xargs -0 --no-run-if-empty notify-send && sleep 3m; do
    true
done
