#!/bin/sh
exec env                                         \
    HOME="${HOME:-/home/noctua}"                 \
    PATH="/usr/local/bin:$HOME/.local/bin:$PATH" \
    DISPLAY="${DISPLAY:-:0}"                     \
    ./notmuch
