#!/bin/sh
export USER="$(whoami)"
export HOME=/home/"$USER"
export DISPLAY=":0"
. "$HOME"/.profile

set -e

# check for internet connection
ip route ls | grep -q '.'

# check if the gpg-agent is running
pgrep gpg-agent > /dev/null

notmuch new --quiet 2>&1

exec sleep 1m
