#!/bin/sh
export USER="$(whoami)"
export HOME=/home/"$USER"
export DISPLAY=":0"
. "$HOME/.profile"

spotifyd --no-daemon 2>&1 \
	| tee -a $XDG_RUNTIME_DIR/playlist \
	| sed '/trunc/d;/loaded$/d;/^Loading/d'
