#!/bin/bash

status=$(quodlibet --status | cut -d' ' -f1)
case "$status" in
    "playing") icon="<icon=music/play.xpm/>" ;;
    "paused")  icon="<icon=music/pause.xpm/>"   ;;
    *) ;;
esac

echo '<action=`quodlibet --toggle-window`>'"$icon"'</action>'

