#!/bin/sh

# notify for new messages
notmuch search tag:new | cut -d' ' --complement -f1 | xargs -0 --no-run-if-empty notify-send

# finally, put new messages in the inbox
notmuch tag +inbox -new -- tag:new

