#!/bin/sh

# some filtering
notmuch tag +killed -new -unread -- subject:'^[SPAM]' to:ugent

# notify for new messages
notmuch search tag:new | cut -d' ' --complement -f1 | xargs -0 --no-run-if-empty notify-send

# processed new messages are no longer new
notmuch tag -new -- tag:new

