#!/bin/sh

# some filtering
notmuch tag +killed -new -- subject:'^[SPAM]' to:ugent

# notify for new messages
notmuch search tag:new | cut -d' ' --complement -f1 | xargs -0 --no-run-if-empty notify-send

# put new messages in the inbox
notmuch tag +inbox -new -- tag:new

